### ISSUE TITLE
Geometric Paasche and Laspeyres and two stage index

### ISSUE THREAD

**Issue by jkrinitz** [grahamjwhite/IndexNumR#23]
First, I really appreciate your work.
I have two ideas for additional methods to include.

1. Is it possible to include the geometric methods for the Laspeyres and Paasche as methods for price index? (Formula 9.6 in https://www.ilo.org/public/english/bureau/stat/download/cpi/ch9_rev_1c.pdf )

2. The second idea is to include a method for stepwise price index calculation (ID1, ID2)
       First step: elementary aggregates (Jevons, Carli, Dutot) per ID1 (e.g. product class) times the overall expenditure share of the elements of the class
       Second step: aggregate by a second ID2 (some division, where several ID1 belong to one ID2) to generate a matrix containing the price indices and the aggregated weights of the containing ID1's for all t

**Comment by grahamjwhite** [comment]
Hi jkrinitz,

Thanks very much for your interest in the package and for the suggestions. I'm fairly well progressed towards the next release, but the first of your suggestions is not a hard one to do. I'll try to put it into the next release. The second suggestion is definitely possible, but I'd spend a bit more time thinking that one through so I might leave it for a future release. 

Thanks again for your contribution!
