### ISSUE TITLE
How to select a base year?

### ISSUE THREAD

**Issue by luzabarajas** [grahamjwhite/IndexNumR#26]
Hello. I wonder if this is the right place to ask this: I am trying to construct a price index based on annual data with a fixed-base but I would like to indicate which year should be considered for the base year. I see that priceindex() does not take an option to input a base time period but it takes period (1) by default. How could i get around with this? Thanks in advance

**Comment by grahamjwhite** [comment]
Hi, thanks for your question. At this stage there is no option to do that in the package. You could try to replicate this behaviour by subsetting two periods at a time from the dataset (the base period as period 1 and the other period as period 2) and computing an index on just these two periods, then combining the results of these bilateral comparisons at the end.
