### ISSUE TITLE
Changing `pervar` to `tvar`

### ISSUE THREAD

**Issue by alberto-agudo** [grahamjwhite/IndexNumR#71]
When debugging code it sometimes becomes cumbersome to differentiate between `pvar` and `pervar` in the `priceIndex` function. I suggest that, given that it is a time variable, it could be called `tvar`.

**Comment by grahamjwhite** [comment]
Hi Alberto. 

Thanks for the suggestion. While I don't disagree with your suggestion, I need to balance the benefit of making the change against the cost of introducing a breaking change into the code. If I rename a parameter then everyone that has code using `pervar` will need need to change their code to the new parameter name. At this stage I don't think the potential benefit of changing it is worth the cost to users' existing code.

**Comment by alberto-agudo** [comment]
Hi Graham,

Thank you for your response. 

I agree with you in that the issue of backwards compatibility weighs more than the advantage of renaming the parameter. It makes perfect sense.
