### ISSUE TITLE
Error: NA in IndexNumber Output

### ISSUE THREAD

**Issue by aks10000** [grahamjwhite/IndexNumR#8]
I am working with following data:

> str(ind_guar)
'data.frame':	27 obs. of  4 variables:
 $ time      : int  1 2 3 4 5 6 7 8 9 1 ...
 $ prodID    : int  1 1 1 1 1 1 1 1 1 2 ...
 $ prices    : int  1907 2350 2268 5586 7334 5404 4225 3364 2797 1540 ...
 $ quantities: int  12275 797 21476 30733 10648 18271 33826 44891 44203 366919 ..

I get NAs in index number output. I am not finding why is it so. My code chunk is as follows---

> methods <- c("laspeyres","paasche","fisher","tornqvist")
> prices_guar <- lapply(methods, function(x) {priceIndex(ind_guar,pvar = "prices", qvar = "quantities", pervar = "time", prodID = "prodID", indexMethod = x, output = "chained")})

> as.data.frame(prices_guar, col.names = methods)
  laspeyres  paasche   fisher tornqvist
1  1.000000 1.000000 1.000000  1.000000
2  1.296701 1.279213 1.287927  1.288266
3  1.540747 1.504613 1.522573  1.523101
4        NA       NA       NA        NA
5        NA       NA       NA        NA
6        NA       NA       NA        NA
7        NA       NA       NA        NA
8        NA       NA       NA        NA
9        NA       NA       NA        NA

I checked everything but all in vain. Please help.

**Comment by grahamjwhite** [comment]
Hi aks10000, 

Are you able to send me either an RData or Excel file with the full dataframe so I can try to replicate your error?

Edit: Sorry, I wasn't particularly clear - could you please send me the data for the dataframe ind_guar

Cheers, 
Graham

**Comment by grahamjwhite** [comment]
I've run your code on the CES_sigma_2 dataset that is distributed with IndexNumR and it ran without issues, so I suspect it is an issue with the data. I need you to send me the ind_guar data frame though, or I can't help you identify the issue. 

Graham

**Comment by grahamjwhite** [comment]
Since I’ve not received a response and I cannot replicate the error, I’m closing this issue.
